version: '2'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: evV2BubA3ZtXchrLuGCthfMfDx8yTr
    expose:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql

  l1j:
    build:
      context: .
    ports:
      - 2000:2000/tcp
    environment:
      DB_HOST: db
      DB_PWD: evV2BubA3ZtXchrLuGCthfMfDx8yTr
    depends_on:
      - db
    links:
      - 'db:db'
    stdin_open: true
    tty: true
    volumes:
      - ./L1J-TW_3.80c:/data
volumes:
  db_data:
