version: '2.3'

services:
  db:
    image: mysql:5.6
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin -h localhost -u root -ppassword ping --silent"]
      timeout: 10s
      retries: 3
  l1jtw:
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    build: .
    restart: always
    environment:
      DB_HOST: db
      DB_PWD: password
      RATE: 10
      ENCHANT_CHANCE: 40
