version: '2'
services:
  db:
    ports:
      - 3306:3306/tcp
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: evV2BubA3ZtXchrLuGCthfMfDx8yTr
      MYSQL_DATABASE: l1jdb
    volumes:
      - db_data:/var/lib/mysql

  l1j:
    build:
      context: .
    ports:
      - 2000:2000/tcp
    environment:
      DB_HOST: db
      DB_PWD: evV2BubA3ZtXchrLuGCthfMfDx8yTr
      RATE: 10
      ENCHANT_CHANCE: 40
    depends_on:
      - db
    links:
      - 'db:db'
volumes:
  db_data:
